language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palette_picker_test;' -U postgres
- knex migrate:latest --env test
- knex seed:run --env test
notifications:
  email: false
deploy:
  provider: heroku
  app: palette-picker-api-williams
  api_key:
    secure: l/qp7rr/V3GdVEarndqBB69YnmjhhSCEb1rvkcGmUGtz54tQ7lLMd8cJ3F0t91IZjAl6Ib9sEiwmK1G+wl7mpLkZ92V09THVXMg0vsc603NZoei+HF8hEvZV8yI26dZYCLLXC+BTkOIUkhRoz6r9aS+8how+v5/bZkGvvYu5lppsXZTm7FtK1uFyzID4qAxzI0PClGKwvisZS+uCGyq/5Xqn3uTM84HPebnQrAZpul3/3tP5j3Ofq11uZe33/FIIFDecqpjF6BxW7i4W0QCb1TqxA9L6Pj3EBdaMsGFjlOsLycg1l1IZYGT8jyC64EbZLD9lag7lqutlkriQUmyUC05BTnOHTOE2Wi0GV3pii+m9vEJc6QHy8ipLfdgcI4TkH81ZF9WP/v1OeKIoz9wYOqh/8tl0sfiwHRnreGODsKpXJYUrpY+1oJuPJoKoKwKJgbPsP1QoReUQmO9W+vzBlkqxS07zngW04NC6JFvfiRGqsb5RJA0rynN+gmDjlpItWcsxCMxuRA3DasvG7oTQVVa0R+BOuX/574cgBQbv9lp68Ds5Zbc7rWygt5F3feM+EGXYPh6FjiE4U8SeIMY0uC32f40PSG+fB+meKF7Cv2/GMGaTP5AIgAcyKeKh0zwt2hIX+P27Zj/ybwwhtaEOo2Xl5wDqhmT6qdKPQqngJvM=
